<a href="https://colab.research.google.com/github/Aryan096yo/demo-file/blob/main/pytorch1_funda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [3]:
#tensor 1. scalors
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back as python int
scalar.item()

7

In [6]:
#vector
vector = torch.tensor([7,7])

In [7]:
vector.ndim

1

In [8]:
#vector.item()

In [9]:
vector.shape

torch.Size([2])

In [10]:
#matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
matrix[1]

tensor([ 9, 10])

In [14]:
matrix[0][1]

tensor(8)

In [15]:
# TEnsor
tensor = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                       [[10,11,12],
                        [13,14,15],
                        [16,17,18]]])
tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [16]:
tensor.ndim

3

In [17]:
tensor[1]

tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [18]:
tensor[0][1]

tensor([4, 5, 6])

In [19]:
tensor[0][0][0]

tensor(1)

In [20]:
tensor.shape

torch.Size([2, 3, 3])

### Random tensors

random tensors are important because the way many nn learns is that they start with tensors full of random numbers and then adjust those numbers to better represent the data

In [21]:
# create a random tensor of (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4251, 0.1292, 0.8668, 0.6122],
        [0.9698, 0.3027, 0.7604, 0.4762],
        [0.7611, 0.2924, 0.4909, 0.0068]])

In [22]:
random_tensor.ndim

2

In [23]:
random_tensor.size()

torch.Size([3, 4])

In [24]:
random_tensor.shape

torch.Size([3, 4])

In [25]:
# creating a random tensor with similar ahpe to an image
random_image = torch.rand(size=(224,224,3)) #height, width, color channels , r, g, b
random_image.shape, random_image.ndim

(torch.Size([224, 224, 3]), 3)

In [26]:
random_image

tensor([[[0.1568, 0.1170, 0.5899],
         [0.0230, 0.8237, 0.2238],
         [0.0059, 0.0719, 0.4958],
         ...,
         [0.6080, 0.6887, 0.0121],
         [0.4806, 0.1681, 0.2119],
         [0.9289, 0.3572, 0.5369]],

        [[0.0049, 0.8686, 0.7558],
         [0.4788, 0.6338, 0.4376],
         [0.5502, 0.1429, 0.3393],
         ...,
         [0.8844, 0.8698, 0.9995],
         [0.6547, 0.7020, 0.1368],
         [0.4494, 0.8048, 0.8528]],

        [[0.1224, 0.1120, 0.1541],
         [0.1278, 0.7266, 0.8794],
         [0.1457, 0.7913, 0.9249],
         ...,
         [0.1443, 0.2696, 0.4921],
         [0.0901, 0.4227, 0.1816],
         [0.8455, 0.6897, 0.6640]],

        ...,

        [[0.2053, 0.2551, 0.0861],
         [0.4829, 0.8754, 0.9703],
         [0.3740, 0.8240, 0.2597],
         ...,
         [0.4387, 0.9388, 0.8429],
         [0.0022, 0.1149, 0.1585],
         [0.3362, 0.3693, 0.0778]],

        [[0.9435, 0.2710, 0.5278],
         [0.3905, 0.1408, 0.8687],
         [0.

### Zeros and ones

In [27]:
# creating a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
ones.dtype

torch.float32

### creating a range of tensors and tensor-like

In [30]:
# use torch.arange()
torch.arange(start= 0, end =  10001, step = 99)

tensor([   0,   99,  198,  297,  396,  495,  594,  693,  792,  891,  990, 1089,
        1188, 1287, 1386, 1485, 1584, 1683, 1782, 1881, 1980, 2079, 2178, 2277,
        2376, 2475, 2574, 2673, 2772, 2871, 2970, 3069, 3168, 3267, 3366, 3465,
        3564, 3663, 3762, 3861, 3960, 4059, 4158, 4257, 4356, 4455, 4554, 4653,
        4752, 4851, 4950, 5049, 5148, 5247, 5346, 5445, 5544, 5643, 5742, 5841,
        5940, 6039, 6138, 6237, 6336, 6435, 6534, 6633, 6732, 6831, 6930, 7029,
        7128, 7227, 7326, 7425, 7524, 7623, 7722, 7821, 7920, 8019, 8118, 8217,
        8316, 8415, 8514, 8613, 8712, 8811, 8910, 9009, 9108, 9207, 9306, 9405,
        9504, 9603, 9702, 9801, 9900, 9999])

In [31]:
one_to_ten = torch.arange(start=1, end = 11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatype
errors in tensors :
1. tensors not right data type
2. tensores not right shape
3. tensor not on right device

In [33]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float32,
                               device = None, #what device ur tensor on cpu, gpu, tpu
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [34]:
float_32_tensor.dtype

torch.float32

In [35]:
 float_16_tensor = float_32_tensor.type(torch.float16)
 float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [36]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [37]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [38]:
int_32_tensor*float_32_tensor

tensor([ 9., 36., 81.])

### Tensor Malipulation

In [39]:
#addition
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [40]:
#multiply
tensor * 10

tensor([10, 20, 30])

In [41]:
# subtraction
tensor - 10

tensor([-9, -8, -7])

In [42]:
# try out pytorch inbuilt function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [43]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### matrix multiplication

two main ways of performing multiplication in neural networks and deep lerning :

1. element wise multiplication
2. matrix multiplication (dot product)

In [44]:
tensor * tensor

tensor([1, 4, 9])

In [45]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [46]:
# matrix multiplication
torch.matmul(tensor,tensor)  # 1 + 4 + 9

tensor(14)

In [47]:
%%time
value = 0
for i in range(len(tensor)) :
  value += tensor[i] * tensor[i]

print(value)


tensor(14)
CPU times: user 968 µs, sys: 837 µs, total: 1.81 ms
Wall time: 1.79 ms


In [48]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 284 µs, sys: 48 µs, total: 332 µs
Wall time: 260 µs


tensor(14)

### one of the most of the commom error in deep learning is shape error

In [49]:
pp = torch.matmul(torch.rand(3,2),torch.rand(2,1)) # the resulting matrix has shape of outer dimensions
pp

tensor([[0.1128],
        [1.0247],
        [1.2629]])

In [50]:
pp.shape

torch.Size([3, 1])

In [52]:
# shapes for matrix multiplication
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_b = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.matmul(tensor_a, tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_a.shape, tensor_b.shape

### to fix our tensor shape issues we can malipulate our one of our tensor through transpose

In [ ]:
tensor_b,tensor_b.shape

In [ ]:
tensor_b.T,tensor_b.T.shape

In [53]:
cc= torch.matmul(tensor_a,tensor_b.T)
cc

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [54]:
cc.shape

torch.Size([3, 3])

### Finding the min, max , mean , sum etc(aggregation)

In [55]:
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [56]:
torch.min(x),x.min()

(tensor(1), tensor(1))

In [57]:
torch.max(x),x.max()

(tensor(91), tensor(91))

In [58]:
# Find the mean-Note : the torch.mean() function requires a tensor of float32 dtype to work
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [59]:
# FInd the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### FInding the position mean and max

In [60]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [61]:
# Find the position in tensor that has the min value with argmin() -> returns index position of target tensor where minumum value occurs
x.argmin()

tensor(0)

In [62]:
x[0]

tensor(1)

In [63]:
x[x.argmax()]

tensor(91)

### Reshaping, stacking, squeezing and unsqeezing tensors

##Reshaping - reshapes an input tensor to a defined shape
##View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
##Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
##Squeeze - removes all '1' dimensions from a tensor
##Unsqueeze - add a '1' dimension to a target tensor
##Permute - Return a view of the input with dimensions (swapped) in a certain way

In [64]:
import torch

In [65]:
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [66]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [67]:
# change the view -> shares the memory with original tensor
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [68]:
# changing z changes x because share same memory
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [69]:
X_stacked = torch.stack([x,x,x,x],dim=1)   # view vstack and hstack also
X_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [70]:
X_stacked[0][2]

tensor(5.)

In [71]:
# squeeze and unsqueeze
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [72]:
x_squeezed = x_reshaped.squeeze()
x_reshaped.squeeze().shape

torch.Size([9])

In [73]:
x_squeezed.shape

torch.Size([9])

In [74]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [75]:
x_unsqueezed.shape

torch.Size([1, 9])

In [76]:
# torch.premute - > reshapes the dimensions of a target in a specified order
x_original = torch.rand(size=(224,224,3)) # height , width , color_channels

x_permuted = x_original.permute(2,0,1) #shifts 0->1 , 1->2 , 2->0


In [77]:
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

# Indexing

In [78]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [79]:
# lets index
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [80]:
x[0][0]

tensor([1, 2, 3])

In [81]:
x[0][0][1]

tensor(2)

In [82]:
x[0][2][2]

tensor(9)

In [83]:
x[:,0]

tensor([[1, 2, 3]])

In [84]:
# Get all values of 0 and 1 dimension and 1st value of 2nd dimension
x[:,:,0]

tensor([[1, 4, 7]])

### pytoch and numpy

In [85]:
# data in numpy, eant in pytoch tensor -> torch.from_numpy(ndarray)
# pytorch tensor->numpy->torch.tensor.numpy() , default numpy dtype is float64 and of tensor is float32
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)

In [86]:
array.dtype

dtype('float64')

In [87]:
tensor.dtype # when converting from numpy to tensor keep dtype in mind

torch.float64

In [88]:
tensor = torch.ones(7)
tensor

tensor([1., 1., 1., 1., 1., 1., 1.])

In [89]:
numpy_tensor = tensor.numpy()
numpy_tensor, tensor.dtype, numpy_tensor.dtype


(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 torch.float32,
 dtype('float32'))

### reproducibility (trying to take random out of random)
in short how a neural network learns
`start with a random numbers -> tensor operations -> update random numbers to try and make them better representation -> again ->again.....




In [90]:
# when you wants a little less randomness
# to resuce the randomness in nn and pytorch comes the concept of a random seed.
# essentially what the random seed does is "flavor" the randomness

In [91]:
import torch
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.1751, 0.5326, 0.6034, 0.8930],
        [0.5537, 0.2502, 0.0469, 0.4208],
        [0.4700, 0.1037, 0.1294, 0.1398]])
tensor([[0.8696, 0.6448, 0.1876, 0.7420],
        [0.5908, 0.0249, 0.4891, 0.4117],
        [0.8360, 0.7440, 0.5194, 0.0050]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [92]:
# Let's make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)  ##<<<<<<<--------
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pytorch on the GPUs (and making faster computation)


### - Getting a gpu
# use google colab
# own
# cloud computing

for 2 , 3 needs setting up


In [93]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


###Check for GPU access for pytoch

In [94]:
import torch
torch.cuda.is_available()

False

For pytorch since its capable of running compute  on the GPU or CPU. It's best practice to setup device agnostic code
 eg run on GPU if available else default to cpu

In [95]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [96]:
# count number of devices
torch.cuda.device_count()

0

In [97]:
# putting tensors and models in the GPU

In [98]:
tensor = torch.tensor([1,2,3])

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [99]:
# move to gpu if ava
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [100]:
### 4. moving tensors back to cpu , if tensors in gpu can't transform in to numpy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [101]:
# to fix the gpu with numpy issue we first bring to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [102]:
tensor_on_gpu

tensor([1, 2, 3])